title: Grace Shang
description: Hello! I am currently an undergraduate student at the University of Toronto, St. George, studying mathematics, statistics, and computer science.
show_downloads: false
theme: jekyll-theme-minimal
